# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{munin-plugins-rails}
  s.version = "0.2.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Eberbach", "Bart ten Brinke"]
  s.date = %q{2011-03-28}
  s.default_executable = %q{request-log-analyzer-munin}
  s.email = %q{andrew@ebertech.ca}
  s.executables = ["request-log-analyzer-munin"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "VERSION",
    "lib/munin-plugins-rails.rb",
    "lib/munin/command.rb",
    "lib/munin/plugins/passenger_memory_stats.rb",
    "lib/munin/plugins/passenger_queue.rb",
    "lib/munin/plugins/passenger_status.rb",
    "lib/munin/plugins/rails_database_time.rb",
    "lib/munin/plugins/rails_request_duration.rb",
    "lib/munin/plugins/rails_request_error.rb",
    "lib/munin/plugins/rails_requests.rb",
    "lib/munin/plugins/rails_view_render_time.rb",
    "lib/munin/rails_plugin.rb",
    "lib/munin/request_log_analyzer_plugin.rb",
    "munin/munin_passenger_memory_stats",
    "munin/munin_passenger_queue",
    "munin/munin_passenger_status",
    "munin/munin_rails_database_time",
    "munin/munin_rails_request_duration",
    "munin/munin_rails_request_error",
    "munin/munin_rails_requests",
    "munin/munin_rails_view_render_time"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Plugins for Munin that use passenger and RLA}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<request-log-analyzer>, [">= 0"])
    else
      s.add_dependency(%q<request-log-analyzer>, [">= 0"])
    end
  else
    s.add_dependency(%q<request-log-analyzer>, [">= 0"])
  end
end

