#!/usr/bin/env ruby
pod=<<-POD

=head1 NAME
passenger_queue - Munin plugin to monitor passenger queue.
Monitors the amount of requests in global queue.

=head1 APPLICABLE SYSTEMS
All systems that have passenger installed.

=head1 CONFIGURATION
The plugin needs to execute passenger-status.
This configuration section shows the defaults of the plugin:

  [passenger_*]
  user root
  command /usr/local/bin/ruby %c
  
Options
  env.passenger_status '/path/to/passenger-status'  # Path to passenger-status
  env.graph_category 'App'                          # Graph Category. Defaults to App.

ln -s /usr/share/munin/plugins/passenger_queue /etc/munin/plugins/passenger_queue

=head1 INTERPRETATION
The plugin shows the current number of requests waiting on global queue.

=head1 MAGIC MARKERS
  #%# family=auto
  #%# capabilities=autoconf

=head1 VERSION
1.5

=head1 BUGS
None known

=head1 AUTHOR
Michaël Witrant - http://michael.witrant.com/
Bart ten Brinke - railsdoctors.com
Daniel Manges - http://gist.github.com/20319

=head1 LICENSE
MIT

POD

# Globals
GRAPH_CATEGORY   = ENV['graph_category'] || 'App'
PASSENGER_STATUS = ENV['passenger_status'] || '/usr/local/bin/passenger-status'

# Check if this plugin can run
def autoconf
  begin
    require 'rubygems'
    gem "passenger", ">=2.0"
  rescue Exception => e
    puts "no (Gem not found: #{e})"
    exit 1
  end
  
  status = `#{PASSENGER_STATUS}`
  unless $?.success?
    puts "no (error whene excuting #{PASSENGER_STATUS})"
    exit 1
  end
  
  puts "yes"
  exit 0
end

# Describe the graph config
def config
  status = `#{PASSENGER_STATUS}`
  
  puts <<-CONFIG
graph_category #{GRAPH_CATEGORY}
graph_title Passenger queue
graph_vlabel count
graph_args --base 1000 -l 0
graph_info The amount of requests waiting on global queue
 
requests.label requests
CONFIG
  exit 0
end
 

# Collect the data
# <tt>debug</tt> Show debug information
def run(debug = false)
  status = `#{PASSENGER_STATUS}`
  
  unless $?.success?
    $stderr.puts "failed executing passenger-status"
    exit 1
  end

  puts status if debug

  status =~ /Waiting on global queue:\s+(\d+)/
  puts "requests.value #{$1}"
end
 

# Main
if ARGV[0] == "config"
  config
elsif ARGV[0] == "autoconf"
  autoconf
elsif ARGV[0] == "debug"
  run(true)
else
  run
end
