#!/usr/bin/env ruby
pod=<<-POD

=head1 NAME
passenger_queue - Munin plugin to monitor passenger queue.
Monitors the amount of requests in global queue.

=head1 APPLICABLE SYSTEMS
All systems that have passenger installed.

=head1 CONFIGURATION
The plugin needs to execute passenger-status.
This configuration section shows the defaults of the plugin:

  [passenger_*]
  user root
  command /usr/local/bin/ruby %c
  
Options
  env.passenger_status '/path/to/passenger-status'  # Path to passenger-status
  env.apache_pid_file '/path/to/apache2.pid'        # Path to passenger-status (like /var/run/apache2.pid)
  env.graph_category 'App'                          # Graph Category. Defaults to App.

ln -s /usr/share/munin/plugins/passenger_queue /etc/munin/plugins/passenger_queue

=head1 INTERPRETATION
The plugin shows the current number of requests waiting on global queue.

=head1 MAGIC MARKERS
  #%# family=auto
  #%# capabilities=autoconf

=head1 VERSION
1.9.7

=head1 BUGS
None known

=head1 AUTHOR
Michaël Witrant - http://michael.witrant.com/
Bart ten Brinke - railsdoctors.com
Daniel Manges - http://gist.github.com/20319

=head1 LICENSE
MIT

POD
require 'rubygems'
require 'munin-plugins-rails'

Munin::PassengerQueue.new(ARGV, ENV).run